import { NextResponse } from 'next/server';
import { revalidateTag } from 'next/cache';
import { requireAdmin } from '../../../admin-auth';
export const dynamic='force-dynamic';
const URL=()=>`${(process.env.SUPABASE_URL||'https://bewxefxjbvbumajflhfw.supabase.co').replace(/\/$/,'')}/rest/v1/site_content`;
const key=()=>process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const headers=()=>({apikey:key(),Authorization:`Bearer ${key()}`,'Content-Type':'application/json'});
function fail(message:string,status=503){return NextResponse.json({message},{status})}
async function auth(){try{await requireAdmin();return true}catch{return false}}
export async function GET(){if(!await auth())return fail('Admin authentication required.',401);if(!key())return fail('Admin database access is not configured. Add SUPABASE_SERVICE_ROLE_KEY.');try{const r=await fetch(`${URL()}?select=*&order=page_key.asc,sort_order.asc,created_at.desc`,{headers:headers(),cache:'no-store'});if(!r.ok)return fail('Unable to load site content.',500);return NextResponse.json({items:await r.json()},{headers:{'Cache-Control':'no-store'}})}catch{return fail('Unable to load site content.',500)}}
export async function POST(request:Request){if(!await auth())return fail('Admin authentication required.',401);if(!key())return fail('Admin database access is not configured. Add SUPABASE_SERVICE_ROLE_KEY.');const b=await request.json().catch(()=>null) as Record<string,unknown>|null;const pageKey=String(b?.page_key??'').trim().slice(0,80);const contentKey=String(b?.content_key??'').trim().slice(0,100);const value=String(b?.content_value??'').slice(0,20000);const type=String(b?.content_type??'text');const sort=Number.isFinite(Number(b?.sort_order))?Number(b?.sort_order):0;const published=b?.is_published!==false;if(!pageKey||!contentKey||!['text','richtext','url','boolean','number','json'].includes(type))return fail('Invalid content fields.',400);try{const r=await fetch(URL(),{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({page_key:pageKey,content_key:contentKey,content_value:value,content_type:type,sort_order:sort,is_published:published})});if(!r.ok)return fail('Unable to create content. Check that the page/key pair is unique.',400);await revalidateTag(`site-content:${pageKey}`,'max');return NextResponse.json({item:(await r.json())[0]})}catch{return fail('Unable to create content.',500)}}
