'use client';
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, FileText, LayoutDashboard, LogOut, MessageSquare, Pencil, Plus, Save, Search, Settings2, Trash2, X } from 'lucide-react';

type Content={id:string;page_key:string;content_key:string;content_type:string;content_value:string;sort_order:number;is_published:boolean};
type Review={id:string;name:string;rating:number;review:string;created_at:string};
const pages=['/','/about','/services','/projects','/profile','/contact','/feedback','/terms','/privacy','/dashboard'];
const blankContent:Omit<Content,'id'>={page_key:'/',content_key:'hero_title',content_type:'text',content_value:'',sort_order:0,is_published:true};

export default function AdminPanel(){const [tab,setTab]=useState<'overview'|'content'|'feedback'|'settings'>('overview');const [items,setItems]=useState<Content[]>([]),[reviews,setReviews]=useState<Review[]>([]),[editing,setEditing]=useState<Content|null>(null),[form,setForm]=useState(blankContent),[reviewEditing,setReviewEditing]=useState<Review|null>(null),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setStatus('Loading…');try{const [a,b]=await Promise.all([fetch('/api/admin/content',{cache:'no-store'}),fetch('/api/admin/feedback',{cache:'no-store'})]);if(a.status===401||b.status===401){location.href='/admin/login';return}const ad=await a.json(),bd=await b.json();if(!a.ok)throw new Error(ad.message);if(!b.ok)throw new Error(bd.message);setItems(ad.items||[]);setReviews(bd.items||[]);setStatus('Ready')}catch(e){setStatus(e instanceof Error?e.message:'Unable to load admin data.')} }
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.page_key} ${x.content_key} ${x.content_value}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 function startNew(){setEditing(null);setForm(blankContent);setTab('content')}
 function startEdit(x:Content){setEditing(x);setForm({...x});setTab('content')}
 async function saveContent(){setBusy(true);setStatus('Saving…');try{const url=editing?`/api/admin/content/${editing.id}`:'/api/admin/content';const r=await fetch(url,{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message);setStatus('Content saved.');setEditing(null);await load()}catch(e){setStatus(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
 async function deleteContent(id:string){if(!confirm('Delete this content record?'))return;setBusy(true);try{const r=await fetch(`/api/admin/content/${id}`,{method:'DELETE'});if(!r.ok)throw new Error((await r.json()).message);await load()}catch(e){setStatus(e instanceof Error?e.message:'Delete failed.')}finally{setBusy(false)}}
 async function saveReview(){if(!reviewEditing)return;setBusy(true);try{const r=await fetch(`/api/admin/feedback/${reviewEditing.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(reviewEditing)});if(!r.ok)throw new Error((await r.json()).message);setReviewEditing(null);await load()}catch(e){setStatus(e instanceof Error?e.message:'Update failed.')}finally{setBusy(false)}}
 async function deleteReview(id:string){if(!confirm('Delete this public review?'))return;setBusy(true);try{const r=await fetch(`/api/admin/feedback/${id}`,{method:'DELETE'});if(!r.ok)throw new Error((await r.json()).message);await load()}catch(e){setStatus(e instanceof Error?e.message:'Delete failed.')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/admin/auth',{method:'DELETE'});location.href='/admin/login'}
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span>AI</span><div><b>CV Builder</b><small>Admin Studio</small></div></div><nav><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><LayoutDashboard/>Overview</button><button className={tab==='content'?'active':''} onClick={()=>setTab('content')}><FileText/>Pages & Content</button><button onClick={()=>{location.href='/admin/analytics'}}><BarChart3/>Visitor Analytics</button><button className={tab==='feedback'?'active':''} onClick={()=>setTab('feedback')}><MessageSquare/>Feedback</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings2/>Settings</button></nav><button className="admin-logout" onClick={logout}><LogOut/>Sign out</button></aside>
 <section className="admin-main"><header className="admin-top"><div><span className="admin-eyebrow">ADMIN CONTROL CENTER</span><h1>{tab==='overview'?'Overview':tab==='content'?'Pages & Content':tab==='feedback'?'Public Feedback':'System Settings'}</h1></div><div className="admin-top-actions"><span className="admin-status">{status}</span>{tab==='content'&&<button className="admin-primary small" onClick={startNew}><Plus size={15}/>New content</button>}</div></header>
 {tab==='overview'&&<><div className="admin-stats"><article><strong>{items.length}</strong><span>Content records</span></article><article><strong>{new Set(items.map(x=>x.page_key)).size}</strong><span>Managed pages</span></article><article><strong>{reviews.length}</strong><span>Public reviews</span></article><article><strong>{items.filter(x=>x.is_published).length}</strong><span>Published entries</span></article></div><div className="admin-card admin-welcome"><span className="admin-eyebrow">FULL CRUD</span><h2>Manage the product from one place.</h2><p>Create, edit, publish, unpublish and delete page content. Review and moderate public feedback. Visitor Analytics is available from the sidebar.</p><div className="admin-quick"><button onClick={()=>setTab('content')}>Manage pages <FileText/></button><button onClick={()=>setTab('feedback')}>Manage feedback <MessageSquare/></button><button onClick={()=>{location.href='/admin/analytics'}}>Visitor analytics <BarChart3/></button></div></div></>}
 {tab==='content'&&<div className="admin-content-grid"><section className="admin-card"><div className="admin-card-head"><div><span className="admin-eyebrow">CONTENT DATABASE</span><h2>{editing?'Edit content':'Create content'}</h2></div>{editing&&<button className="icon-btn" onClick={()=>{setEditing(null);setForm(blankContent)}}><X/></button>}</div><div className="admin-form-grid"><label>Page<select value={form.page_key} onChange={e=>setForm({...form,page_key:e.target.value})}>{pages.map(p=><option key={p}>{p}</option>)}</select></label><label>Content key<input value={form.content_key} onChange={e=>setForm({...form,content_key:e.target.value})} placeholder="hero_title"/></label><label>Type<select value={form.content_type} onChange={e=>setForm({...form,content_type:e.target.value})}><option>text</option><option>richtext</option><option>url</option><option>boolean</option><option>number</option><option>json</option></select></label><label>Sort order<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label><label className="wide">Value<textarea rows={9} value={form.content_value} onChange={e=>setForm({...form,content_value:e.target.value})} placeholder="Enter the page content…"/></label><label className="check wide"><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/> Published</label></div><button className="admin-primary" disabled={busy||!form.page_key||!form.content_key} onClick={saveContent}><Save size={16}/>{editing?'Update content':'Create content'}</button></section>
 <section className="admin-card"><div className="admin-card-head"><div><span className="admin-eyebrow">ALL RECORDS</span><h2>Page content</h2></div><div className="admin-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…"/></div></div><div className="admin-table-wrap"><table><thead><tr><th>Page</th><th>Key</th><th>Value</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><code>{x.page_key}</code></td><td><b>{x.content_key}</b></td><td className="truncate">{x.content_value}</td><td><span className={x.is_published?'pill good':'pill'}>{x.is_published?'Published':'Hidden'}</span></td><td className="actions"><button onClick={()=>startEdit(x)}><Pencil/></button><button onClick={()=>deleteContent(x.id)}><Trash2/></button></td></tr>)}{!filtered.length&&<tr><td colSpan={5}>No content records yet.</td></tr>}</tbody></table></div></section></div>}
 {tab==='feedback'&&<section className="admin-card"><div className="admin-card-head"><div><span className="admin-eyebrow">MODERATION</span><h2>Public reviews</h2></div><button className="admin-secondary" onClick={load}>Refresh</button></div><div className="review-admin-list">{reviews.map(r=><article key={r.id}><div className="review-admin-top"><div><b>{r.name}</b><span>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span></div><div className="actions"><button onClick={()=>setReviewEditing({...r})}><Pencil/></button><button onClick={()=>deleteReview(r.id)}><Trash2/></button></div></div>{reviewEditing?.id===r.id?<div className="admin-form-grid"><label>Name<input value={reviewEditing.name} onChange={e=>setReviewEditing({...reviewEditing,name:e.target.value})}/></label><label>Rating<input type="number" min={1} max={5} value={reviewEditing.rating} onChange={e=>setReviewEditing({...reviewEditing,rating:Number(e.target.value)})}/></label><label className="wide">Review<textarea rows={4} value={reviewEditing.review} onChange={e=>setReviewEditing({...reviewEditing,review:e.target.value})}/></label><div className="wide"><button className="admin-primary small" onClick={saveReview}>Save review</button></div></div>:<p>{r.review}</p>}</article>)}{!reviews.length&&<p className="empty-admin">No reviews found.</p>}</div></section>}
 {tab==='settings'&&<section className="admin-card"><span className="admin-eyebrow">CONFIGURATION</span><h2>Secure deployment settings</h2><p className="settings-copy">Admin authentication uses a server-side <code>ADMIN_PASSWORD</code>. Database CRUD uses the server-only <code>SUPABASE_SERVICE_ROLE_KEY</code>. Neither secret is sent to the browser.</p><div className="setting-row"><b>Session lifetime</b><span>8 hours</span></div><div className="setting-row"><b>Admin cookie</b><span>HttpOnly · Secure · SameSite Strict</span></div><div className="setting-row"><b>Database access</b><span>Server-only service role</span></div></section>}
 </section></main>}
