import { NextResponse } from 'next/server';
import { requireAdmin } from '../../../../admin-auth';
export const dynamic='force-dynamic';
const base=()=>`${(process.env.SUPABASE_URL||'https://bewxefxjbvbumajflhfw.supabase.co').replace(/\/$/,'')}/rest/v1/site_content`;
const key=()=>process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const headers=()=>({apikey:key(),Authorization:`Bearer ${key()}`,'Content-Type':'application/json'});
async function guard(){try{await requireAdmin();return true}catch{return false}}
function err(message:string,status:number){return NextResponse.json({message},{status})}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!await guard())return err('Admin authentication required.',401);if(!key())return err('Admin database access is not configured. Add SUPABASE_SERVICE_ROLE_KEY.',503);const {id}=await params;const b=await request.json().catch(()=>null) as Record<string,unknown>|null;const patch:Record<string,unknown>={};if(b&&'page_key'in b)patch.page_key=String(b.page_key??'').trim().slice(0,80);if(b&&'content_key'in b)patch.content_key=String(b.content_key??'').trim().slice(0,100);if(b&&'content_value'in b)patch.content_value=String(b.content_value??'').slice(0,20000);if(b&&'content_type'in b)patch.content_type=String(b.content_type??'text');if(b&&'sort_order'in b)patch.sort_order=Number(b.sort_order)||0;if(b&&'is_published'in b)patch.is_published=b.is_published!==false;try{const r=await fetch(`${base()}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(patch)});if(!r.ok)return err('Unable to update content.',400);return NextResponse.json({item:(await r.json())[0]||null})}catch{return err('Unable to update content.',500)}}
export async function DELETE(_request:Request,{params}:{params:Promise<{id:string}>}){if(!await guard())return err('Admin authentication required.',401);if(!key())return err('Admin database access is not configured. Add SUPABASE_SERVICE_ROLE_KEY.',503);const {id}=await params;try{const r=await fetch(`${base()}?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{...headers(),Prefer:'return=minimal'}});if(!r.ok)return err('Unable to delete content.',400);return NextResponse.json({ok:true})}catch{return err('Unable to delete content.',500)}}
