import { GoogleGenAI } from '@google/genai';
import { NextResponse } from 'next/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
const MODEL = 'gemini-2.5-flash';
const ACTIONS = ['summary','experience','skills','tailor','cover','cover-letter','ats'] as const;
type Action = typeof ACTIONS[number];
type WritingSettings = { tone?:string; length?:string; audience?:string; language?:string; focus?:string };

function providerMessage(error:unknown){const message=error instanceof Error?error.message:String(error),n=message.toLowerCase();if(n.includes('api key')||n.includes('unauthenticated')||n.includes('permission')||n.includes('forbidden'))return 'Gemini API authentication failed. Check GEMINI_API_KEY and Gemini API access for the selected project.';if(n.includes('quota')||n.includes('resource exhausted')||n.includes('rate limit'))return 'Gemini API quota/rate limit was reached. Please wait and try again.';if(n.includes('not found')||n.includes('model')||n.includes('unsupported'))return `Gemini model ${MODEL} is unavailable for this API key/project. Verify Gemini API access for the selected Google AI Studio project.`;if(n.includes('billing')||n.includes('payment'))return 'Gemini API billing/access is required for this request. Check the selected project settings.';return 'Gemini AI request failed. Please try again. If it continues, check the Vercel function logs.'}
function taskFor(action:Action){switch(action){case'summary':return 'Rewrite the professional summary into concise, high-value CV language. Preserve every fact and never invent employers, dates, tools, education, achievements or metrics.';case'experience':return 'Rewrite experience bullets with strong action verbs, responsibility and impact. Use metrics only when they already exist. Return one polished bullet per line. Never invent facts.';case'skills':return 'Clean and prioritize skills already present. Normalize duplicates and wording, but never add an unsupported skill. Return a comma-separated list.';case'tailor':return 'Tailor the CV toward the job description using only truthful information. Identify keyword opportunities and rewrite relevant wording. Clearly separate current matches, gaps and recommended additions.';case'cover':case'cover-letter':return 'Write a professional concise cover letter based only on the CV and job description. Do not invent company knowledge, achievements, years of experience or qualifications. Use placeholders when a required detail is missing.';case'ats':return 'Perform a practical ATS analysis. Extract important job-description keywords, compare them with the CV, identify missing or weak areas, and give truthful recommendations. Never recommend claiming unsupported skills or experience.'}}

export async function POST(req:Request){try{const body=await req.json();const action=(body?.action==='cover-letter'?'cover':body?.action) as Action;const cv=body?.cv,jobDescription=body?.jobDescription,settings:WritingSettings=body?.settings||body?.writingSettings||{};const apiKey=process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY;if(!apiKey)return NextResponse.json({error:'GEMINI_API_KEY is not configured on the server.'},{status:503,headers:{'Cache-Control':'no-store'}});if(!ACTIONS.includes(action))return NextResponse.json({error:'Invalid AI action.'},{status:400,headers:{'Cache-Control':'no-store'}});const prompt=`You are the professional AI writing engine inside an AI CV Builder.\n\nRULES:\n- Ground every factual statement in the supplied CV.\n- Never fabricate experience, skills, employers, dates, education, certifications, tools, achievements or metrics.\n- If information is missing, say it is missing instead of guessing.\n- Optimize for recruiter readability and ATS parsing: clear language, standard terminology, strong action verbs, relevant keywords, no keyword stuffing.\n- Never output markdown decoration such as #, **, __, or fenced code.\n- For CV-ready writing, return clean plain text only.\n- For ATS/tailoring, clearly separate matches, gaps and truthful recommendations.\n\nWRITING SETTINGS:\nTone: ${settings.tone||'Professional'}\nLength: ${settings.length||'Concise'}\nAudience: ${settings.audience||'Recruiters / ATS'}\nLanguage: ${settings.language||'English'}\nFocus: ${settings.focus||'Achievements & impact'}\n\nTASK:\n${taskFor(action)}\n\nCANDIDATE CV JSON:\n${JSON.stringify(cv||{}).slice(0,24000)}\n\nJOB DESCRIPTION:\n${String(jobDescription||'').slice(0,18000)||'(No job description provided)'}\n\nReturn only the useful result for the user.`;const ai=new GoogleGenAI({apiKey});const result=await ai.models.generateContent({model:MODEL,contents:prompt,config:{maxOutputTokens:1800}});const text=result.text?.trim();if(!text)return NextResponse.json({error:'Gemini returned an empty response. Please try again.'},{status:502,headers:{'Cache-Control':'no-store'}});return NextResponse.json({text},{headers:{'Cache-Control':'no-store'}})}catch(error){console.error('Gemini AI error:',error);return NextResponse.json({error:providerMessage(error)},{status:502,headers:{'Cache-Control':'no-store'}})}}
