import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Privacy Policy', description: 'How AI CV Builder handles CV content, local storage, AI requests, feedback and contact information.' };

export default function PrivacyPage(){return <main className="legal-page"><span className="eyebrow">LEGAL · PRIVACY</span><h1>Privacy Policy</h1><p className="legal-lead">AI CV Builder is designed so ordinary editing can stay in your browser. This page explains what is stored locally, what leaves the browser and what happens when you use public features.</p>
<section><h2>1. CVs and browser storage</h2><p>CV drafts, templates, design settings, section order and imported CV content are stored in your browser using local storage. The current editor does not require an account to keep a local CV. Clearing site data or browser storage can remove those saved drafts, so use the backup export if a CV is important.</p></section>
<section><h2>2. AI writing requests</h2><p>When you choose an AI feature, the relevant CV information, your selected writing settings and, for job-targeting tools, the job description are sent to the configured AI provider through the application server. The server-side API key is not placed in the browser. AI responses are not used as a substitute for your own review.</p></section>
<section><h2>3. Imported documents and profile photos</h2><p>PDF, DOCX, TXT, Markdown and JSON imports are processed in the editor workflow. Profile photos are resized locally before they are stored in the current browser workspace. The application does not need to upload a photo just to display it in a CV.</p></section>
<section><h2>4. Public feedback</h2><p>If you submit a review on the public feedback page, the name, star rating, review text and submission time are stored in the project database so the review can be displayed to other visitors. Do not include private contact details or sensitive information in a public review.</p></section>
<section><h2>5. Contact links and external services</h2><p>GitHub, Vercel, WhatsApp and the configured AI provider are external services. Opening one of those services takes you outside AI CV Builder and their own privacy policies apply. The application does not need access to your private GitHub or WhatsApp account to provide the public links shown here.</p></section>
<section><h2>6. Security and retention</h2><p>The public database uses access controls intended for public reviews, and public API endpoints include basic abuse protection. Local CV data remains under the browser storage of the device where you created it unless you explicitly send text through an AI feature or submit information through a public form.</p></section>
<section><h2>7. Questions</h2><p>For privacy questions or a request about information submitted through the public site, contact a.m.a63425@gmail.com.</p></section>
<small>Last updated: September 11, 2026</small></main>}
