'use client';

import { useEffect, useMemo, useState } from 'react';
import { GripVertical, Minus, Plus, RotateCcw } from 'lucide-react';

type LayoutItem = { column: 'main' | 'side'; order: number };
type LayoutMap = Record<string, LayoutItem>;
const KEY = 'ai-cv-builder-layout-v2';
const headingToKey: Record<string, string> = { PROFILE:'profile', EXPERIENCE:'experience', PROJECTS:'projects', SKILLS:'skills', EDUCATION:'education', CERTIFICATIONS:'certifications', LANGUAGES:'languages', INTERESTS:'interests' };
function cvId(){return new URLSearchParams(window.location.search).get('cv')||'cv-1'}
function storageKey(){return `${KEY}-${cvId()}`}
function readLayout():LayoutMap{try{return JSON.parse(localStorage.getItem(storageKey())||'{}')}catch{return {}}}
function writeLayout(value:LayoutMap){localStorage.setItem(storageKey(),JSON.stringify(value))}
function keyOf(el:Element){return headingToKey[el.querySelector('h3')?.textContent?.trim().toUpperCase()||'']||''}
function snapshot():LayoutMap{const result:LayoutMap={};document.querySelectorAll<HTMLElement>('.resume-main,.resume-side').forEach(parent=>{const column=parent.classList.contains('resume-side')?'side':'main';Array.from(parent.children).forEach((el,index)=>{const key=keyOf(el);if(key)result[key]={column,order:index}})});return result}
function applyLayout(layout:LayoutMap){const paper=document.querySelector('.paper');const main=paper?.querySelector<HTMLElement>('.resume-main');const side=paper?.querySelector<HTMLElement>('.resume-side');if(!main||!side)return;const nodes=new Map<string,HTMLElement>();paper.querySelectorAll<HTMLElement>('.resume-section').forEach(el=>{const key=keyOf(el);if(key)nodes.set(key,el)});Object.entries(layout).forEach(([key,item])=>{const el=nodes.get(key),parent=item.column==='side'?side:main;if(el&&el.parentElement!==parent)parent.appendChild(el)});[main,side].forEach(parent=>Array.from(parent.children).sort((a,b)=>(layout[keyOf(a)]?.order??999)-(layout[keyOf(b)]?.order??999)).forEach(el=>{const current=parent.lastElementChild;if(current!==el)parent.appendChild(el)}))}

export default function CVInteractions(){
 const [zoom,setZoom]=useState(100),[contact,setContact]=useState<'left'|'center'|'right'>('left'),[dragMode,setDragMode]=useState(true),[ready,setReady]=useState(false);const zoomLabel=useMemo(()=>`${zoom}%`,[zoom]);
 useEffect(()=>{if(window.location.pathname!=='/')return;const savedZoom=Number(localStorage.getItem(`${KEY}-zoom`)||'100');const savedContact=(localStorage.getItem(`${KEY}-contact-${cvId()}`)||'left') as 'left'|'center'|'right';if(savedZoom>=70&&savedZoom<=140)setZoom(savedZoom);if(['left','center','right'].includes(savedContact))setContact(savedContact);setReady(true);let observer:MutationObserver|undefined;const refresh=()=>{document.body.dataset.cvContact=savedContact;applyLayout(readLayout())};const start=()=>{refresh();observer=new MutationObserver(()=>{observer?.disconnect();requestAnimationFrame(()=>{refresh();if(observer)observer.observe(document.querySelector('.preview-area')||document.body,{childList:true,subtree:true})})});observer.observe(document.querySelector('.preview-area')||document.body,{childList:true,subtree:true})};requestAnimationFrame(start);return()=>observer?.disconnect()},[]);
 useEffect(()=>{if(!ready)return;localStorage.setItem(`${KEY}-zoom`,String(zoom));const paper=document.querySelector<HTMLElement>('.paper');if(paper)paper.style.setProperty('--cv-editor-zoom',String(zoom/100))},[zoom,ready]);
 useEffect(()=>{if(!ready)return;localStorage.setItem(`${KEY}-contact-${cvId()}`,contact);document.body.dataset.cvContact=contact},[contact,ready]);
 useEffect(()=>{if(!ready||!dragMode)return;const root=document.querySelector('.paper');if(!root)return;let dragging=false;const makeDraggable=()=>root.querySelectorAll<HTMLElement>('.resume-section').forEach(el=>{el.draggable=true;el.dataset.cvKey=keyOf(el)});const onDragStart=(event:Event)=>{const ev=event as DragEvent;const target=(ev.target as HTMLElement).closest('.resume-section') as HTMLElement|null;if(!target)return;dragging=true;target.classList.add('cv-dragging');ev.dataTransfer?.setData('text/cv-section',keyOf(target));if(ev.dataTransfer)ev.dataTransfer.effectAllowed='move'};const onDragOver=(event:Event)=>{const ev=event as DragEvent;const target=(ev.target as HTMLElement).closest('.resume-section') as HTMLElement|null;if(!target)return;ev.preventDefault();target.classList.add('cv-drop-target')};const onDrop=(event:Event)=>{const ev=event as DragEvent;ev.preventDefault();const sourceKey=ev.dataTransfer?.getData('text/cv-section');const target=(ev.target as HTMLElement).closest('.resume-section') as HTMLElement|null;if(!sourceKey||!target)return;const source=root.querySelector<HTMLElement>(`.resume-section[data-cv-key="${sourceKey}"]`);if(!source||source===target||!target.parentElement)return;const parent=target.parentElement;if(ev.clientY<target.getBoundingClientRect().top+target.getBoundingClientRect().height/2)parent.insertBefore(source,target);else parent.insertBefore(source,target.nextSibling);root.querySelectorAll('.cv-drop-target,.cv-dragging').forEach(x=>x.classList.remove('cv-drop-target','cv-dragging'));writeLayout(snapshot());applyLayout(readLayout());dragging=false};const onDragEnd=()=>{if(dragging){dragging=false;root.querySelectorAll('.cv-drop-target,.cv-dragging').forEach(x=>x.classList.remove('cv-drop-target','cv-dragging'))}};makeDraggable();root.addEventListener('dragstart',onDragStart);root.addEventListener('dragover',onDragOver);root.addEventListener('drop',onDrop);root.addEventListener('dragend',onDragEnd);const observer=new MutationObserver(makeDraggable);observer.observe(root,{childList:true,subtree:true});return()=>{root.removeEventListener('dragstart',onDragStart);root.removeEventListener('dragover',onDragOver);root.removeEventListener('drop',onDrop);root.removeEventListener('dragend',onDragEnd);observer.disconnect()}},[ready,dragMode]);
 if(!ready)return null;const changeZoom=(delta:number)=>setZoom(v=>Math.max(70,Math.min(140,v+delta)));const reset=()=>{localStorage.removeItem(storageKey());applyLayout({});setZoom(100);setContact('left')};return <div className="cv-floating-tools" aria-label="CV page controls"><button title="Zoom out" onClick={()=>changeZoom(-10)}><Minus size={14}/></button><span>{zoomLabel}</span><button title="Zoom in" onClick={()=>changeZoom(10)}><Plus size={14}/></button><span className="cv-tool-divider"/><button title="Contact left" className={contact==='left'?'active':''} onClick={()=>setContact('left')}>L</button><button title="Contact center" className={contact==='center'?'active':''} onClick={()=>setContact('center')}>C</button><button title="Contact right" className={contact==='right'?'active':''} onClick={()=>setContact('right')}>R</button><span className="cv-tool-divider"/><button title={dragMode?'Disable drag':'Enable drag'} className={dragMode?'active':''} onClick={()=>setDragMode(v=>!v)}><GripVertical size={14}/></button><button title="Reset page layout" onClick={reset}><RotateCcw size={14}/></button></div>;
}
