'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { GripVertical, LocateFixed, Minus, Plus, RotateCcw, SlidersHorizontal, X } from 'lucide-react';

type LayoutItem = { column: 'main' | 'side'; order: number };
type LayoutMap = Record<string, LayoutItem>;
type ContactAlign = 'left' | 'center' | 'right';
type HeaderPart = 'identity' | 'avatar';
type FloatingPoint = { x: number; y: number };
type SectionHandle = { key: string; x: number; y: number };

const KEY='ai-cv-builder-layout-v5';
const FLOAT_KEY='ai-cv-builder-floating-position-v3';
const headingToKey:Record<string,string>={PROFILE:'profile',EXPERIENCE:'experience',PROJECTS:'projects',SKILLS:'skills',EDUCATION:'education',CERTIFICATIONS:'certifications',LANGUAGES:'languages',INTERESTS:'interests'};
function cvId(){return new URLSearchParams(window.location.search).get('cv')||'cv-1'}
function storageKey(){return `${KEY}-${cvId()}`}
function readLayout():LayoutMap{try{return JSON.parse(localStorage.getItem(storageKey())||'{}')}catch{return {}}}
function writeLayout(v:LayoutMap){localStorage.setItem(storageKey(),JSON.stringify(v))}
function keyOf(el:Element){return headingToKey[el.querySelector('h3')?.textContent?.trim().toUpperCase()||'']||''}
function readHeaderOrder():HeaderPart[]{try{const v=JSON.parse(localStorage.getItem(`${KEY}-header-${cvId()}`)||'null');if(Array.isArray(v)&&v.every(x=>x==='identity'||x==='avatar'))return v}catch{}return ['identity','avatar']}
function writeHeaderOrder(v:HeaderPart[]){localStorage.setItem(`${KEY}-header-${cvId()}`,JSON.stringify(v))}
function applySafeOrder(layout:LayoutMap){
 const paper=document.querySelector<HTMLElement>('.paper');if(!paper)return;
 paper.querySelectorAll<HTMLElement>('.resume-section').forEach(el=>{const key=keyOf(el);el.style.order=layout[key]?String(layout[key].order):''});
 const head=paper.querySelector<HTMLElement>('.resume-head');if(head){const order=readHeaderOrder();const identity=head.querySelector<HTMLElement>('.resume-identity');const avatar=head.querySelector<HTMLElement>('.avatar');if(identity)identity.style.order=String(Math.max(0,order.indexOf('identity')));if(avatar)avatar.style.order=String(Math.max(0,order.indexOf('avatar')))}}
function viewportSize(){const vv=window.visualViewport;return{width:vv?.width||window.innerWidth,height:vv?.height||window.innerHeight}}
function readFloatingPoint():FloatingPoint{try{const v=JSON.parse(localStorage.getItem(FLOAT_KEY)||'null');if(Number.isFinite(v?.x)&&Number.isFinite(v?.y))return v}catch{}const {width,height}=viewportSize();return{x:Math.max(12,width-70),y:Math.max(12,height-150)}}
function clampPoint(p:FloatingPoint){const {width,height}=viewportSize();const size=54;return{x:Math.max(8,Math.min(Math.max(8,width-size-8),p.x)),y:Math.max(8,Math.min(Math.max(8,height-size-8),p.y))}}

export default function CVInteractions(){
 const[zoom,setZoom]=useState(100),[contact,setContact]=useState<ContactAlign>('left'),[headerAlign,setHeaderAlign]=useState<ContactAlign>('left'),[dragMode,setDragMode]=useState(true),[ready,setReady]=useState(false);
 const[toolsOpen,setToolsOpen]=useState(false),[floating,setFloating]=useState<FloatingPoint>({x:0,y:0}),[draggingTools,setDraggingTools]=useState(false),[sectionHandles,setSectionHandles]=useState<SectionHandle[]>([]);
 const floatingRef=useRef<FloatingPoint>({x:0,y:0});
 const zoomLabel=useMemo(()=>`${zoom}%`,[zoom]);
 const updateFloating=(point:FloatingPoint)=>{const next=clampPoint(point);floatingRef.current=next;setFloating(next)};
 useEffect(()=>{if(window.location.pathname!=='/')return;const savedZoom=localStorage.getItem(`${KEY}-zoom`);const fitZoom=Math.max(60,Math.min(100,Math.round(((viewportSize().width-16)/794)*100)));const z=Number(savedZoom||fitZoom);const c=(localStorage.getItem(`${KEY}-contact-${cvId()}`)||'left')as ContactAlign;const h=(localStorage.getItem(`${KEY}-header-align-${cvId()}`)||'left')as ContactAlign;if(z>=60&&z<=160)setZoom(z);if(['left','center','right'].includes(c))setContact(c);if(['left','center','right'].includes(h))setHeaderAlign(h);const initial=clampPoint(readFloatingPoint());floatingRef.current=initial;setFloating(initial);setReady(true);const refresh=()=>{document.body.dataset.cvContact=(localStorage.getItem(`${KEY}-contact-${cvId()}`)||'left')as ContactAlign;document.body.dataset.cvHeaderAlign=(localStorage.getItem(`${KEY}-header-align-${cvId()}`)||'left')as ContactAlign;applySafeOrder(readLayout())};const onResize=()=>{updateFloating(floatingRef.current);requestAnimationFrame(refresh)};window.addEventListener('resize',onResize);window.visualViewport?.addEventListener('resize',onResize);window.visualViewport?.addEventListener('scroll',onResize);const timer=window.setTimeout(refresh,80);return()=>{window.removeEventListener('resize',onResize);window.visualViewport?.removeEventListener('resize',onResize);window.visualViewport?.removeEventListener('scroll',onResize);window.clearTimeout(timer)}},[]);
 useEffect(()=>{if(!ready)return;localStorage.setItem(`${KEY}-zoom`,String(zoom));const paper=document.querySelector<HTMLElement>('.paper');const wrap=document.querySelector<HTMLElement>('.paper-wrap');if(paper)paper.style.setProperty('--cv-paper-scale',String(zoom/100));if(wrap)wrap.style.setProperty('--cv-paper-scale',String(zoom/100))},[zoom,ready]);
 useEffect(()=>{if(!ready)return;localStorage.setItem(`${KEY}-contact-${cvId()}`,contact);document.body.dataset.cvContact=contact},[contact,ready]);
 useEffect(()=>{if(!ready)return;localStorage.setItem(`${KEY}-header-align-${cvId()}`,headerAlign);document.body.dataset.cvHeaderAlign=headerAlign},[headerAlign,ready]);
 useEffect(()=>{if(!ready)return;localStorage.setItem(FLOAT_KEY,JSON.stringify(floating))},[floating,ready]);
 useEffect(()=>{if(!ready||!dragMode)return;const root=document.querySelector<HTMLElement>('.paper');if(!root)return;let longPress=0;let touchActive=false;let touchSource:HTMLElement|null=null;let touchPointerId:number|null=null;let startX=0;let startY=0;let pendingLayout:LayoutMap|null=null;
  const makeDraggable=()=>{root.querySelectorAll<HTMLElement>('.resume-section').forEach(el=>{el.draggable=true;el.dataset.cvKey=keyOf(el)});root.querySelectorAll<HTMLElement>('.resume-identity,.resume-head > .avatar').forEach(el=>{el.draggable=true;el.dataset.cvHeaderPart=el.classList.contains('avatar')?'avatar':'identity'})};
  const clearMarks=()=>root.querySelectorAll('.cv-drop-target,.cv-dragging,.cv-header-drop-target,.cv-touch-dragging').forEach(x=>x.classList.remove('cv-drop-target','cv-dragging','cv-header-drop-target','cv-touch-dragging'));
  const cancelTouch=()=>{if(longPress){window.clearTimeout(longPress);longPress=0}touchActive=false;touchSource=null;touchPointerId=null;pendingLayout=null;clearMarks()};
  const buildOrder=(parent:HTMLElement,source:HTMLElement,target:HTMLElement)=>{const siblings=Array.from(parent.querySelectorAll<HTMLElement>(':scope > .resume-section')).sort((a,b)=>Number(getComputedStyle(a).order||0)-Number(getComputedStyle(b).order||0));const sourceIndex=siblings.indexOf(source);const targetIndex=siblings.indexOf(target);if(sourceIndex<0||targetIndex<0)return null;const order=siblings.map(keyOf).filter(Boolean);order.splice(sourceIndex,1);const nextIndex=Math.max(0,Math.min(order.length,targetIndex));order.splice(nextIndex,0,keyOf(source));const layout=readLayout();order.forEach((k,i)=>{layout[k]={column:parent.classList.contains('resume-side')?'side':'main',order:i};const el=parent.querySelector<HTMLElement>(`.resume-section[data-cv-key="${CSS.escape(k)}"]`);if(el)el.style.order=String(i)});return layout};
  const reorderTouch=(ev:PointerEvent)=>{if(!touchActive||!touchSource)return;ev.preventDefault();const hit=document.elementsFromPoint(ev.clientX,ev.clientY).find(x=>x instanceof HTMLElement&&x.matches('.resume-section')) as HTMLElement|undefined;if(!hit||hit===touchSource)return;const parent=touchSource.parentElement;if(!parent||hit.parentElement!==parent)return;pendingLayout=buildOrder(parent,touchSource,hit);if(pendingLayout)touchSource.classList.add('cv-touch-dragging')};
  const onPointerDown=(event:Event)=>{const ev=event as PointerEvent;if(ev.pointerType!=='touch'&&ev.pointerType!=='pen')return;const target=(ev.target as HTMLElement).closest('.resume-section') as HTMLElement|null;if(!target)return;startX=ev.clientX;startY=ev.clientY;touchSource=target;touchPointerId=ev.pointerId;longPress=window.setTimeout(()=>{if(!touchSource||touchPointerId===null)return;touchActive=true;touchSource.classList.add('cv-touch-dragging');try{touchSource.setPointerCapture(touchPointerId)}catch{}},320)};
  const onPointerMove=(event:Event)=>{const ev=event as PointerEvent;if(!touchSource||ev.pointerId!==touchPointerId)return;const distance=Math.hypot(ev.clientX-startX,ev.clientY-startY);if(!touchActive&&distance>8){cancelTouch();return}if(touchActive)reorderTouch(ev)};
  const onPointerUp=(event:Event)=>{const ev=event as PointerEvent;if(!touchSource||ev.pointerId!==touchPointerId)return;if(touchActive&&pendingLayout){writeLayout(pendingLayout);applySafeOrder(pendingLayout)}try{if(touchSource.hasPointerCapture(ev.pointerId))touchSource.releasePointerCapture(ev.pointerId)}catch{};cancelTouch()};
  const onPointerCancel=()=>cancelTouch();
  const onDragStart=(event:Event)=>{const ev=event as DragEvent;const target=(ev.target as HTMLElement).closest('.resume-section,.resume-identity,.resume-head > .avatar')as HTMLElement|null;if(!target)return;target.classList.add('cv-dragging');const hp=target.dataset.cvHeaderPart;if(hp)ev.dataTransfer?.setData('text/cv-header-part',hp);else ev.dataTransfer?.setData('text/cv-section',keyOf(target));if(ev.dataTransfer)ev.dataTransfer.effectAllowed='move'};
  const onDragOver=(event:Event)=>{const ev=event as DragEvent;const hp=ev.dataTransfer?.types.includes('text/cv-header-part');const target=(ev.target as HTMLElement).closest('.resume-section,.resume-head')as HTMLElement|null;if(!target)return;if(hp&&target.classList.contains('resume-head')){ev.preventDefault();target.classList.add('cv-header-drop-target')}else if(!hp&&target.classList.contains('resume-section')){ev.preventDefault();target.classList.add('cv-drop-target')}};
  const onDrop=(event:Event)=>{const ev=event as DragEvent;ev.preventDefault();const hp=ev.dataTransfer?.getData('text/cv-header-part')as HeaderPart|'';const target=(ev.target as HTMLElement).closest('.resume-section,.resume-head')as HTMLElement|null;
   if(hp&&target?.classList.contains('resume-head')){const other=hp==='avatar'?'identity':'avatar';const before=ev.clientX<target.getBoundingClientRect().left+target.getBoundingClientRect().width/2;writeHeaderOrder(before?[hp,other]:[other,hp]);applySafeOrder(readLayout());clearMarks();return}
   const sourceKey=ev.dataTransfer?.getData('text/cv-section');if(!sourceKey||!target?.classList.contains('resume-section'))return;const source=root.querySelector<HTMLElement>(`.resume-section[data-cv-key="${CSS.escape(sourceKey)}"]`);if(!source||source===target)return;const sp=source.parentElement,tp=target.parentElement;if(!sp||!tp||sp!==tp)return;const layout=buildOrder(sp,source,target);if(layout)writeLayout(layout);clearMarks()};
  const onDragEnd=()=>clearMarks();
  makeDraggable();root.addEventListener('pointerdown',onPointerDown,{passive:true});root.addEventListener('pointermove',onPointerMove,{passive:false});root.addEventListener('pointerup',onPointerUp,{passive:false});root.addEventListener('pointercancel',onPointerCancel,{passive:true});root.addEventListener('dragstart',onDragStart);root.addEventListener('dragover',onDragOver);root.addEventListener('drop',onDrop);root.addEventListener('dragend',onDragEnd);const observer=new MutationObserver(makeDraggable);observer.observe(root,{childList:true,subtree:true});return()=>{if(longPress)window.clearTimeout(longPress);root.removeEventListener('pointerdown',onPointerDown);root.removeEventListener('pointermove',onPointerMove);root.removeEventListener('pointerup',onPointerUp);root.removeEventListener('pointercancel',onPointerCancel);root.removeEventListener('dragstart',onDragStart);root.removeEventListener('dragover',onDragOver);root.removeEventListener('drop',onDrop);root.removeEventListener('dragend',onDragEnd);observer.disconnect();clearMarks()}},[ready,dragMode]);
 useEffect(()=>{if(!ready||!dragMode)return;const root=document.querySelector<HTMLElement>('.paper');if(!root)return;let raf=0;const refresh=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const next:SectionHandle[]=[];root.querySelectorAll<HTMLElement>('.resume-section[data-cv-key]').forEach(el=>{const rect=el.getBoundingClientRect();if(rect.width<2||rect.height<2)return;next.push({key:el.dataset.cvKey||'',x:Math.max(2,Math.min(window.innerWidth-34,rect.left-26)),y:Math.max(4,Math.min(window.innerHeight-34,rect.top+8))})});setSectionHandles(next)})};refresh();const preview=document.querySelector<HTMLElement>('.preview-area');window.addEventListener('resize',refresh,{passive:true});window.visualViewport?.addEventListener('resize',refresh,{passive:true});window.visualViewport?.addEventListener('scroll',refresh,{passive:true});preview?.addEventListener('scroll',refresh,{passive:true});const observer=new ResizeObserver(refresh);observer.observe(root);return()=>{window.removeEventListener('resize',refresh);window.visualViewport?.removeEventListener('resize',refresh);window.visualViewport?.removeEventListener('scroll',refresh);preview?.removeEventListener('scroll',refresh);observer.disconnect();if(raf)cancelAnimationFrame(raf)}},[ready,dragMode,zoom]);
 useEffect(()=>{if(!ready||!dragMode)return;const buttons=Array.from(document.querySelectorAll<HTMLElement>('.cv-section-handle'));const cleanups:Array<()=>void>=[];buttons.forEach(button=>{const key=button.dataset.cvKey;if(!key)return;let active=false;let source:HTMLElement|null=null;let layout:LayoutMap|null=null;const move=(e:PointerEvent)=>{if(!active||!source)return;e.preventDefault();const target=document.elementsFromPoint(e.clientX,e.clientY).find(x=>x instanceof HTMLElement&&x.matches('.resume-section')) as HTMLElement|undefined;if(!target||target===source||target.parentElement!==source.parentElement)return;const parent=source.parentElement;const siblings=Array.from(parent.querySelectorAll<HTMLElement>(':scope > .resume-section')).sort((a,b)=>Number(getComputedStyle(a).order||0)-Number(getComputedStyle(b).order||0));const order=siblings.map(keyOf).filter(Boolean);const si=order.indexOf(key);const ti=order.indexOf(keyOf(target));if(si<0||ti<0)return;order.splice(si,1);order.splice(Math.max(0,Math.min(order.length,ti)),0,key);const next=readLayout();order.forEach((k,i)=>{next[k]={column:parent.classList.contains('resume-side')?'side':'main',order:i};const el=parent.querySelector<HTMLElement>(`.resume-section[data-cv-key="${CSS.escape(k)}"]`);if(el)el.style.order=String(i)});layout=next;source.classList.add('cv-touch-dragging')};const stop=(e?:PointerEvent)=>{if(!active)return;active=false;if(layout)writeLayout(layout);try{if(e&&button.hasPointerCapture(e.pointerId))button.releasePointerCapture(e.pointerId)}catch{};source?.classList.remove('cv-touch-dragging');source=null;layout=null};const begin=(e:PointerEvent)=>{if(e.pointerType==='mouse'&&e.button!==0)return;source=document.querySelector<HTMLElement>(`.resume-section[data-cv-key="${CSS.escape(key)}"]`);if(!source)return;active=true;layout=null;e.preventDefault();try{button.setPointerCapture(e.pointerId)}catch{}};button.addEventListener('pointerdown',begin,{passive:false});button.addEventListener('pointermove',move,{passive:false});button.addEventListener('pointerup',stop);button.addEventListener('pointercancel',stop);cleanups.push(()=>{button.removeEventListener('pointerdown',begin);button.removeEventListener('pointermove',move);button.removeEventListener('pointerup',stop);button.removeEventListener('pointercancel',stop)});});return()=>cleanups.forEach(fn=>fn())},[ready,dragMode,sectionHandles.length]);
 useEffect(()=>{if(!ready)return;const fab=document.querySelector<HTMLElement>('.cv-floating-fab');if(!fab)return;let active=false,moved=false,start={x:0,y:0},origin={x:0,y:0};let raf=0;const move=(e:PointerEvent)=>{if(!active)return;e.preventDefault();const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.hypot(dx,dy)>5)moved=true;const next=clampPoint({x:origin.x+dx,y:origin.y+dy});floatingRef.current=next;if(!raf)raf=requestAnimationFrame(()=>{raf=0;setFloating(floatingRef.current)})};const stop=(e?:PointerEvent)=>{if(!active)return;active=false;setDraggingTools(false);if(raf){cancelAnimationFrame(raf);raf=0;setFloating(floatingRef.current)}try{if(e&&fab.hasPointerCapture(e.pointerId))fab.releasePointerCapture(e.pointerId)}catch{};if(!moved)setToolsOpen(v=>!v)};const begin=(e:PointerEvent)=>{if(e.button!==0&&e.pointerType==='mouse')return;if((e.target as HTMLElement).closest('.cv-floating-tools'))return;e.preventDefault();active=true;moved=false;start={x:e.clientX,y:e.clientY};origin=floatingRef.current;setDraggingTools(true);try{fab.setPointerCapture(e.pointerId)}catch{}};fab.addEventListener('pointerdown',begin,{passive:false});fab.addEventListener('pointermove',move,{passive:false});fab.addEventListener('pointerup',stop);fab.addEventListener('pointercancel',stop);return()=>{fab.removeEventListener('pointerdown',begin);fab.removeEventListener('pointermove',move);fab.removeEventListener('pointerup',stop);fab.removeEventListener('pointercancel',stop);if(raf)cancelAnimationFrame(raf)}},[ready]);
 if(!ready)return null;
 const changeZoom=(d:number)=>setZoom(v=>Math.max(60,Math.min(160,v+d)));
 const reset=()=>{localStorage.removeItem(storageKey());localStorage.removeItem(`${KEY}-header-${cvId()}`);document.querySelectorAll<HTMLElement>('.resume-section,.resume-identity,.resume-head > .avatar').forEach(el=>el.style.order='');const fit=Math.max(60,Math.min(100,Math.round(((viewportSize().width-16)/794)*100)));setZoom(fit);setContact('left');setHeaderAlign('left');const p=clampPoint({x:Math.max(12,viewportSize().width-70),y:Math.max(12,viewportSize().height-150)});updateFloating(p);setToolsOpen(false)};
 const dock=()=>{const {width,height}=viewportSize();const current=floatingRef.current;const edge=current.x<width/2?8:Math.max(8,width-62);updateFloating({x:edge,y:Math.min(Math.max(8,current.y),Math.max(8,height-62))});setToolsOpen(false)};
 const {width}=viewportSize();const panelSide=floating.x>width/2?'panel-left':'panel-right';const panelVertical=floating.y<150?'panel-below':'';
 const style={left:floating.x,top:floating.y};
 return <><div className="cv-section-handles" aria-hidden="true">{sectionHandles.map(handle=><button key={handle.key} className="cv-section-handle" data-cv-key={handle.key} style={{left:handle.x,top:handle.y}} title="Drag section" tabIndex={-1}><GripVertical size={16}/></button>)}</div><div className={`cv-floating-shell ${toolsOpen?'is-open':''} ${draggingTools?'is-dragging':''} ${panelSide} ${panelVertical}`} style={style}>
   <div className="cv-floating-tools" aria-label="CV page controls" aria-hidden={!toolsOpen}>
    <div className="cv-tools-head"><span>CV controls</span><button title="Close controls" onClick={()=>setToolsOpen(false)}><X size={15}/></button></div>
    <div className="cv-tools-grid">
     <div className="cv-tool-group"><span className="cv-tool-label">Zoom</span><div className="cv-tool-row"><button title="Zoom out" onClick={()=>changeZoom(-10)}><Minus size={14}/></button><strong>{zoomLabel}</strong><button title="Zoom in" onClick={()=>changeZoom(10)}><Plus size={14}/></button></div></div>
     <div className="cv-tool-group"><span className="cv-tool-label">Contact</span><div className="cv-tool-row"><button title="Contact left" className={contact==='left'?'active':''} onClick={()=>setContact('left')}>L</button><button title="Contact center" className={contact==='center'?'active':''} onClick={()=>setContact('center')}>C</button><button title="Contact right" className={contact==='right'?'active':''} onClick={()=>setContact('right')}>R</button></div></div>
     <div className="cv-tool-group"><span className="cv-tool-label">Header</span><div className="cv-tool-row"><button title="Header left" className={headerAlign==='left'?'active':''} onClick={()=>setHeaderAlign('left')}>L</button><button title="Header center" className={headerAlign==='center'?'active':''} onClick={()=>setHeaderAlign('center')}>C</button><button title="Header right" className={headerAlign==='right'?'active':''} onClick={()=>setHeaderAlign('right')}>R</button></div></div>
     <div className="cv-tool-group cv-tool-wide"><span className="cv-tool-label">Layout</span><div className="cv-tool-row"><button title={dragMode?'Disable CV content drag':'Enable CV content drag'} className={dragMode?'active':''} onClick={()=>setDragMode(v=>!v)}><GripVertical size={14}/><span>{dragMode?'Drag on':'Drag off'}</span></button><button title="Dock control to nearest edge" onClick={dock}><LocateFixed size={14}/></button><button title="Reset page layout" onClick={reset}><RotateCcw size={14}/></button></div></div>
    </div>
    <div className="cv-tools-tip"><GripVertical size={13}/> On phone use the small handle beside a section to drag it. The round button is freely movable.</div>
   </div>
   <button className="cv-floating-fab" type="button" aria-label={toolsOpen?'Close CV controls':'Open CV controls'} title="Drag me • click to open" aria-expanded={toolsOpen}><span className="cv-fab-ring"/><SlidersHorizontal size={21}/></button>
 </div></>;
}
